### ISSUE TITLE
`audience` is not the ID I chose when setting up an API

### ISSUE THREAD

**Issue by opyate** [auth0-samples/auth0-python-api-samples#13]
This line https://github.com/auth0-samples/auth0-python-api-samples/blob/master/00-Starter-Seed/server.py#L103 defines `audience` as the unique identifier for the API, which is a URL.

However, when I paste the JWT token into jwt.io, audience is actually the ID of my SPA client. (I use Angular 1)

Needless to say I'm getting an `jose.exceptions.JWTClaimsError: Invalid audience`

**Comment by opyate** [comment]
https://github.com/auth0-samples/auth0-angularjs-samples/tree/master/03-Calling-an-API says "The value for AUTH0_AUDIENCE is the identifier used for an API that you create in the Auth0 dashboard." and not the ID for the SPA.

**Comment by chenkie** [comment]
Which token are you checking in jwt.io? It sounds like you might be pasting in your id_token but it should be the access_token.

**Comment by opyate** [comment]
Yes, that was my mistake, thanks Ryan.
