### ISSUE TITLE
Example should use Request context

### ISSUE THREAD

**Issue by dagostinelli** [auth0-samples/auth0-python-api-samples#16]
In this file, the code is using `flask._app_ctx_stack.top.current_user` 

https://github.com/auth0-samples/auth0-python-api-samples/blob/f9bea71ced80296ae0bec5b8eb34c55a06eb828c/00-Starter-Seed/server.py#L118

I think it should be `flask._request_ctx_stack.top.current_user`

Right?

Wouldn't we want the current_user to be in the current request context and not the whole app's context?

**Comment by aaguiarz** [comment]
It's fixed, thanks for reporting it.
