### ISSUE TITLE
Backend Python: Several problems with the API_ID variable.

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-python-api-samples#20]
The variable API_ID hasn't the appropriate name in the quickstart sample project.
That can be seen in the following files:
.env
readme.md
server.py
And Missing file location at the top of the snippet code
Also, the variable is not properly filled. 
The correct name for this variable is: AUTH0_AUDIENCE
Missing file location at the top of the snippet code

![image](https://user-images.githubusercontent.com/26749061/33177974-d3c06058-d03a-11e7-9bfa-fb324d9adb71.png)

**Comment by aaguiarz** [comment]
The variable should be API_IDENTIFIER
