### ISSUE TITLE
Backend Quickstart: Error after execution of the command pip install -r requirements.txt

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-python-api-samples#21]
Error after execution of the command pip install -r requirements.txt
The dependency python-jose is currently outdated.
Also, there are several problems with python 3.6

![image](https://user-images.githubusercontent.com/26749061/33178047-17f7441c-d03b-11e7-85a9-c4421dff6c3c.png)

**Comment by HH0718** [comment]
I'm not sure why but I think pycrypto is no longer maintained/supported. I also read that pycryptodome is a good alternative but I'm not sure how much this would change the tutorial.
