### ISSUE TITLE
Set error handler without public APP variable

### ISSUE THREAD

**Issue by estebancortero** [auth0-samples/auth0-python-api-samples#35]
[In the example](https://github.com/auth0-samples/auth0-python-api-samples/blob/master/00-Starter-Seed/server.py#L30), the flask app is a public variable `APP`, which is used to set the error handler in the decorator:

```python
@APP.errorhandler(AuthError)
def handle_auth_error(ex):
  ...
``` 

What's the best way to do this if I don't have a public `APP` variable for my Flask app but instead an app factory function `create_app`, which returns the app?

**Comment by jimmyjames** [comment]
Apologies not receiving a response - @estebancortero were you able to figure this out? Given the age of this issue I'm going to close it, but if you are still experiencing this issue, please reopen.
