### ISSUE TITLE
Error calling jwt.Decode

### ISSUE THREAD

**Issue by nnats** [auth0-samples/auth0-python-api-samples#4]
When calling Python API always throws exception jwt.DecodeError on jwt.decode(token,secret,audience).

![image](https://cloud.githubusercontent.com/assets/20141842/22450909/d33434ce-e748-11e6-8a43-ee5f5cc5478c.png)

**Comment by Annyv2** [comment]
Hi! Could you provide more details about the version of the libraries you're using?

**Comment by nnats** [comment]
Installed:
- Python 3.6.0
- Flask 0.12
- Flask-cors 3.0.2
- PyJWT 1.4.2
