### ISSUE TITLE
Add a test with sample curl to test?

### ISSUE THREAD

**Issue by jay-dihenkar** [auth0-samples/auth0-python-api-samples#40]

**Comment by jay-dihenkar** [comment]
for "00-Starter-Seed"

**Comment by lbalmaceda** [comment]
@jay-dihenkar I think you missed the "next step" on the quickstart:

![image](https://user-images.githubusercontent.com/3900123/62219229-51be6d00-b384-11e9-9e24-0602266522c6.png)

https://auth0.com/docs/quickstart/backend/python/02-using#calling-the-api-from-your-application
